<?php get_header(); ?>


<main class="main-content mdl-layout__content">
    <div class="posts-container mdl-grid">
        <div class="post mdl-cell mdl-cell--6-col-desktop" id="div1">
            <h6>Grumpy wizards make toxic brew for the evil Queen and Jack.</h6>
            <p>Non quia quisquam minus voluptatem eos laborum aut. Voluptas similique a et officia. Consequatur beatae quibusdam eligendi. Et itaque illo suscipit non ipsum. Labore repudiandae eum sint voluptas et ea reprehenderit. Maiores tempore est nesciunt numquam quia maxime. Sunt voluptates voluptas non nostrum tempora. Modi pariatur deserunt voluptates asperiores ovident ut exercitationem qui. Et dolor est eum exercitationem facere et. Facilis dolor consequatur natus optio dolores autem. Voluptatem quia saepe esse. Ut nisi ut aperiam et eaque illo. Voluptates alias animi voluptatem asperiores dolores. Maiores architecto rerum eveniet autem provident nisi. Totam ratione et ad rerum officia eos dolore quas. Voluptatem saepe quidem impedit eum. Expedita culpa qui commodi asperiores. Qui rem dolores exercitationem quidem nulla quia. Enim et voluptatem vel dolorem eos culpa veritatis velit.</p>
        </div>
        <div class="post mdl-cell mdl-cell--3-col-desktop" id="div2">
            <h6>Grumpy wizards make toxic brew for the evil Queen and Jack.</h6>
            <p>Non quia quisquam minus voluptatem eos laborum aut. Voluptas similique a et officia. Consequatur beatae quibusdam eligendi. Et itaque illo suscipit non ipsum. Labore repudiandae eum sint voluptas et ea reprehenderit. Maiores tempore est nesciunt numquam quia maxime. Sunt voluptates voluptas non nostrum tempora. Modi pariatur deserunt voluptates asperiores ovident ut exercitationem qui. Et dolor est eum exercitationem facere et. Facilis dolor consequatur natus optio dolores autem. Voluptatem quia saepe esse. Ut nisi ut aperiam et eaque illo. Voluptates alias animi voluptatem asperiores dolores. Maiores architecto rerum eveniet autem provident nisi. Totam ratione et ad rerum officia eos dolore quas. Voluptatem saepe quidem impedit eum. Expedita culpa qui commodi asperiores. Qui rem dolores exercitationem quidem nulla quia. Enim et voluptatem vel dolorem eos culpa veritatis velit.</p>
        </div>
        <div class="post mdl-cell mdl-cell--3-col-desktop" id="div3">
            <h6>Grumpy wizards make toxic brew for the evil Queen and Jack.</h6>
            <p>Non quia quisquam minus voluptatem eos laborum aut. Voluptas similique a et officia. Consequatur beatae quibusdam eligendi. Et itaque illo suscipit non ipsum. Labore repudiandae eum sint voluptas et ea reprehenderit. Maiores tempore est nesciunt numquam quia maxime. Sunt voluptates voluptas non nostrum tempora. Modi pariatur deserunt voluptates asperiores ovident ut exercitationem qui. Et dolor est eum exercitationem facere et. Facilis dolor consequatur natus optio dolores autem. Voluptatem quia saepe esse. Ut nisi ut aperiam et eaque illo. Voluptates alias animi voluptatem asperiores dolores. Maiores architecto rerum eveniet autem provident nisi. Totam ratione et ad rerum officia eos dolore quas. Voluptatem saepe quidem impedit eum. Expedita culpa qui commodi asperiores. Qui rem dolores exercitationem quidem nulla quia. Enim et voluptatem vel dolorem eos culpa veritatis velit.</p>
        </div>
        <div class="post mdl-cell mdl-cell--12-col-desktop" id="div4">
            <h6>Grumpy wizards make toxic brew for the evil Queen and Jack.</h6>
            <p>Non quia quisquam minus voluptatem eos laborum aut. Voluptas similique a et officia. Consequatur beatae quibusdam eligendi. Et itaque illo suscipit non ipsum. Labore repudiandae eum sint voluptas et ea reprehenderit. Maiores tempore est nesciunt numquam quia maxime. Sunt voluptates voluptas non nostrum tempora. Modi pariatur deserunt voluptates asperiores ovident ut exercitationem qui. Et dolor est eum exercitationem facere et. Facilis dolor consequatur natus optio dolores autem. Voluptatem quia saepe esse. Ut nisi ut aperiam et eaque illo. Voluptates alias animi voluptatem asperiores dolores. Maiores architecto rerum eveniet autem provident nisi. Totam ratione et ad rerum officia eos dolore quas. Voluptatem saepe quidem impedit eum. Expedita culpa qui commodi asperiores. Qui rem dolores exercitationem quidem nulla quia. Enim et voluptatem vel dolorem eos culpa veritatis velit.</p>
        </div>
    </div><!-- /.posts-container -->
<?php get_footer(); ?>